### ISSUE TITLE
0.239657保存不上

### ISSUE THREAD

**Issue by PengWanWan01** [huangzhibiao/BGDB_OC#12]
请问为什么保存不上0.239657这样的CGFloat，保留的结果只为0；
1.239657保留的结果只为1；
小数点后面的能保留吗？

**Comment by PengWanWan01** [comment]
+(BOOL)updateSet:(Class)model_class sql:(NSString*)sql{
    NSAssert(sql,@"sql语句不能为空!");
    dispatch_semaphore_wait([BGSqlite shareInstance].BG_Semaphore, DISPATCH_TIME_FOREVER);
    BOOL result = NO;
    @autoreleasepool {
        if([self isExistSqliteWithClass:model_class]){
            if([self openTable:model_class]){
                //静态的更新不需要更新数据库检查.
                NSMutableString* SQL = [NSMutableString stringWithFormat:@"update %@ ",[BGTool getTableNameWithCalss:model_class]];
//                    if ([sql containsString:@"."]) {
//                        sql = [sql stringByReplacingOccurrencesOfString:@"." withString:BG_PropertySeparator];
//                    }
                [SQL appendString:sql];
                Begin_Transcation
                result = [self execSql:SQL];
                Commit_Transcation
            }
            [self close];
        }else{
            BGDebug(@"符合条件的数据不存在,请先存入数据再进行更新!")
        }
    }
    dispatch_semaphore_signal([BGSqlite shareInstance].BG_Semaphore);
    return result;

}

我把上面几行代码注释就好了，请问为什么这里要加一个这样的判断呢？我把它注释是否会引起其他错误呢。大神，请指教呀

**Comment by huangzhibiao** [comment]
不要动库代码，小数点问题是数据库类型转换引起的，如果你想用小数点就用NSNumber类型.
