### ISSUE TITLE
查询不存在表的数据个数你的返回为0，但是dispatch_semaphore_signal没有调用。再执行其他方法会直接卡死

### ISSUE THREAD

**Issue by ghost** [huangzhibiao/BGDB_OC#13]

**Comment by ghost** [comment]
(NSInteger)sqliteMethodWithClass:(Class)model_class type:(bg_sqliteMethodType)methodType key:(NSString*)key where:(NSString*)where这个函数中也存在

**Comment by huangzhibiao** [comment]
不是太明白你的问题，请描述的详细些.

**Comment by ghost** [comment]
因为业务情况，会出现我查询不存在的表，我想知道表数据个数。然后我再进行删除操作，会卡死。
原因是因为查询表的个数函数中，你会判断表存不存在，不存在你会直接返回。但是你返回时，没有发送信号量，我执行删除操作会一直处于等待状态。

**Comment by huangzhibiao** [comment]
贴出你的使用代码我看一下

**Comment by ghost** [comment]
- (BOOL)deleteDataWithDataSetID:(NSInteger)datasetID {
    
    NSString *where = [NSString stringWithFormat:@"where datasetID=%zi",datasetID];
    NSInteger count = [ISMDataModel bg_countWhere:where];//这个表不一定存在
    BOOL removeOK;
    if (count > 0) {
        removeOK = [ISMDataModel bg_deleteWhere:where];
    } else {
        removeOK = YES;
    }
    
    BOOL deleteOK = NO;
    if (removeOK) {
        deleteOK = [ISMDataLayerModel bg_deleteWhere:where];
    }
    
    return removeOK && deleteOK;
}

**Comment by huangzhibiao** [comment]
我看到bug了，稍等哈，改完了通知你。

**Comment by huangzhibiao** [comment]
bug修复了，代码已上传到github.

**Comment by ghost** [comment]
好的
