### ISSUE TITLE
BGSqlite有很多方法是崩溃的

### ISSUE THREAD

**Issue by AwakenDragon** [huangzhibiao/BGDB_OC#16]
通过uniqueKey获取对象中的uniqueKeyVlaue时一直报错，比如BGSqlite的509和518行代码，id uniqueKeyVlaue = [self valueForKey:uniqueKey]，应该改为id uniqueKeyVlaue = [object valueForKey:uniqueKey]吧，self代表BGSqlite，不是要存储的对象，怎么可能取到相应的值

**Comment by huangzhibiao** [comment]
看到了，因为BGFMDB优化过后，以BGFMDB为主了,这个库很久没有更新了

**Comment by huangzhibiao** [comment]
谢谢反馈.
