### ISSUE TITLE
insert another sqlite table

### ISSUE THREAD

**Issue by Sebacho-Barajas** [huangzhibiao/BGDB_OC#5]
I persisted some objects in a table called **Categories** and I didn't get any issue there so far but now I want to persist some objects in another table called **Channels** but I get this error :
![screen shot 2017-05-13 at 4 33 55 am](https://cloud.githubusercontent.com/assets/10381993/26023956/83430c7c-3795-11e7-87f1-1f4a044d5eb3.png)

this is my code :        
```
 NSArray *channelData = [channelsResults valueForKey:@"data"];
        
        for (id details in channelData ) {
            
            [Channels setDebug:YES];
    
            Channels *channelsData = [Channels new];

            channelsData.channelID = [details valueForKey:@"id"];
            channelsData.name = [details valueForKey:@"name"];
            channelsData.picture = [details valueForKey:@"picture"];
            channelsData.categoryID = [details valueForKey:@"category_id"];
            channelsData.desc = [details valueForKey:@"description"];
            [channelData saveOrUpdate];
        }
        
```

**Comment by huangzhibiao** [comment]
you can`t use NSArray type save, you should use custom class model. like that:

 Channels *channelsData = [Channels new];

        for (id details in channelData ) {
            [Channels setDebug:YES];
           channelsData.channelID = [details valueForKey:@"id"];
            channelsData.name = [details valueForKey:@"name"];
            channelsData.picture = [details valueForKey:@"picture"];
            channelsData.categoryID = [details valueForKey:@"category_id"];
            channelsData.desc = [details valueForKey:@"description"];
            [channelData saveOrUpdate];
        }
 NSArray* all = [channelData findAll];

**Comment by Sebacho-Barajas** [comment]
I see my error 😂😂 thanks , I was persisting the array channelData not the object channelsData.
