### ISSUE TITLE
is there a way to delete a single object from database?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [huangzhibiao/BGDB_OC#6]
this is my table : 
![screen shot 2017-05-19 at 7 04 05 pm](https://cloud.githubusercontent.com/assets/10381993/26269964/13685002-3cc6-11e7-9f8e-3eb851e84066.png)

I want to delete the object in "favoriteID" not the whole row

 this is my code: 

```
   NSString *cond = [NSString stringWithFormat:@"where favoriteID = '%@'",self.subchannelModel.subID];
    [Subchannels deleteWhere:cond];
```
when I use this code it will delete the whole row!

**Comment by huangzhibiao** [comment]
SQLite does not support the deletion of table fields.

**Comment by huangzhibiao** [comment]
SQLite does not support the deletion of table fields  in column.
