### ISSUE TITLE
问下，这个框架支持 联合主键吗？（多个属性作为主键）

### ISSUE THREAD

**Issue by fei1234** [huangzhibiao/BGDB_OC#7]

**Comment by fei1234** [comment]
/**
 想要定义'唯一约束',实现该函数返回相应的key即可.
 */
+(NSArray *)bg_uniqueKeys{
    return @[@"name",@"sex"];
}

使用了这个方法，但是 在db软件中查看主键还是ID。。。。

**Comment by fei1234** [comment]
我想找一个牛逼的框架，看你的这个还不错

**Comment by fei1234** [comment]
pod ‘BGFMDB’, '~> 1.39’    找不到库

**Comment by GIKICoder** [comment]
可以看一下GDataBase  可以实现多主键.

**Comment by huangzhibiao** [comment]
现在使用BGFMDB吧，支持联合主键，同时效率也做了很多优化，跟这个库效率差不多了，这个库基本不再更新了，以BGFMDB为主现在.
