### ISSUE TITLE
接口看是简约了不少，不过排序之类的没提供，你说的是为了性能优化，那么BGFMDB框架对FMDB做了一次封装后性能很低吗？

### ISSUE THREAD

**Issue by CNDEVE** [huangzhibiao/BGDB_OC#9]

**Comment by huangzhibiao** [comment]
因为中间要经过一层FMDB和处理监听数据变化等，所以是有一定消耗的.  BGFMDB也不能说性能低，要看你怎么用和适合自己的APP就好，没有最好，只有适合.

**Comment by CNDEVE** [comment]
是这样啊，你说的精简版的性能高些，只是接口好像少了些，比如排序查询之类的要自己写sql语句吗？谢谢！

**Comment by huangzhibiao** [comment]
是的，排序等你自己写sql语句.

**Comment by huangzhibiao** [comment]
如果你想知道性能，那你就看一下两个库的核心源码，你就知道了，BGDB_OC是直接对接sqlite的原生API，而BGFMDB则需要经过FMDB，所有当数据量很大的时候性能损耗就体现出来了.

**Comment by CNDEVE** [comment]
谢谢这么耐心的解答
